// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARa33q0d4eSVbM_kUW5UBisYBk-6So16k',
    appId: '1:485117348628:android:726778bbbb06564f7a5001',
    messagingSenderId: '485117348628',
    projectId: 'nandur-397e9',
    storageBucket: 'nandur-397e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXoypVL8FdF1dvoNCxOdIOz8mWQmjqGK4',
    appId: '1:485117348628:ios:e07b70f4fcbdaab47a5001',
    messagingSenderId: '485117348628',
    projectId: 'nandur-397e9',
    storageBucket: 'nandur-397e9.appspot.com',
    androidClientId: '485117348628-1fn2a393bi0v1i68538n946f4d41v9kq.apps.googleusercontent.com',
    iosClientId: '485117348628-ngjb2tr66frqmgcbqlt67gfjvagoklmj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterOnboarding',
  );
}
